/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sjtu.napu.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.sjtu.napu.struts.form.StuinfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-22-2015
 * 
 * XDoclet definition:
 * @struts.action path="/stuinfo" name="stuinfoForm" input="/save.jsp" scope="request"
 * @struts.action-forward name="success" path="/result.jsp"
 */
public class StuinfoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StuinfoForm stuinfoForm = (StuinfoForm) form;// TODO Auto-generated method stub
		request.setAttribute("username", stuinfoForm.getUsername());
		return mapping.findForward("success");
	}
}