/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sjtu.napu.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-22-2015
 * 
 * XDoclet definition:
 * @struts.form name="registerForm"
 */
public class RegisterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** mail property */
	private String mail;

	/** sex property */
	private String sex;

	/** address property */
	private String address;

	/** age property */
	private Integer age;

	/** name property */
	private String name;

	/** repassword property */
	private String repassword;

	/** password property */
	private String password;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the mail.
	 * @return String
	 */
	public String getMail() {
		return mail;
	}

	/** 
	 * Set the mail.
	 * @param mail The mail to set
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}

	/** 
	 * Returns the sex.
	 * @return String
	 */
	public String getSex() {
		return sex;
	}

	/** 
	 * Set the sex.
	 * @param sex The sex to set
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/** 
	 * Returns the address.
	 * @return String
	 */
	public String getAddress() {
		return address;
	}

	/** 
	 * Set the address.
	 * @param address The address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/** 
	 * Returns the age.
	 * @return Integer
	 */
	public Integer getAge() {
		return age;
	}

	/** 
	 * Set the age.
	 * @param age The age to set
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the repassword.
	 * @return String
	 */
	public String getRepassword() {
		return repassword;
	}

	/** 
	 * Set the repassword.
	 * @param repassword The repassword to set
	 */
	public void setRepassword(String repassword) {
		this.repassword = repassword;
	}

	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}