/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sjtu.napu.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-22-2015
 * 
 * XDoclet definition:
 * @struts.form name="stuinfoForm"
 */
public class StuinfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** summary property */
	private String summary;

	/** classes property */
	private String classes;

	/** sex property */
	private String sex;

	/** username property */
	private String username;

	/** likes property */
	private String likes;

	/** score property */
	private String score;

	/** years property */
	private String years;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the summary.
	 * @return String
	 */
	public String getSummary() {
		return summary;
	}

	/** 
	 * Set the summary.
	 * @param summary The summary to set
	 */
	public void setSummary(String summary) {
		this.summary = summary;
	}

	/** 
	 * Returns the classes.
	 * @return String
	 */
	public String getClasses() {
		return classes;
	}

	/** 
	 * Set the classes.
	 * @param classes The classes to set
	 */
	public void setClasses(String classes) {
		this.classes = classes;
	}

	/** 
	 * Returns the sex.
	 * @return String
	 */
	public String getSex() {
		return sex;
	}

	/** 
	 * Set the sex.
	 * @param sex The sex to set
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/** 
	 * Returns the likes.
	 * @return String
	 */
	public String getLikes() {
		return likes;
	}

	/** 
	 * Set the likes.
	 * @param likes The likes to set
	 */
	public void setLikes(String likes) {
		this.likes = likes;
	}

	/** 
	 * Returns the score.
	 * @return String
	 */
	public String getScore() {
		return score;
	}

	/** 
	 * Set the score.
	 * @param score The score to set
	 */
	public void setScore(String score) {
		this.score = score;
	}

	/** 
	 * Returns the years.
	 * @return String
	 */
	public String getYears() {
		return years;
	}

	/** 
	 * Set the years.
	 * @param years The years to set
	 */
	public void setYears(String years) {
		this.years = years;
	}
}